<a href="https://colab.research.google.com/github/pszachew/Music-Genre-Classification/blob/master/IRMAS/training_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay
import joblib
import seaborn as sns
import matplotlib.pyplot as plt
from statistics import mean
import json

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
X = pd.read_csv('/content/gdrive/MyDrive/csv_data/IRMAS_embedded.csv',header=None)

In [5]:
y = pd.read_csv('/content/gdrive/MyDrive/csv_data/IRMAS_labels.csv', header=None)

In [7]:
scaler = StandardScaler()
scaler.fit(X)
X_sc =pd.DataFrame(scaler.transform(X))

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_sc,y,test_size=0.3, random_state=10)

## **Logistic Regression**

In [9]:
from sklearn.linear_model import LogisticRegression

In [11]:
log_reg_mod = LogisticRegression(max_iter=10000)

In [12]:
log_reg_mod.fit(X_train, np.array(y_train).flatten())

LogisticRegression(max_iter=10000)

In [18]:
joblib.dump(log_reg_mod, 'IRMAS_log_reg.sav')

['IRMAS_log_reg.sav']

In [19]:
y_pre_lg = log_reg_mod.predict(X_test)

In [20]:
print(classification_report(y_test,y_pre_lg))

              precision    recall  f1-score   support

         cel       0.70      0.71      0.71       127
         cla       0.70      0.66      0.68       158
         flu       0.68      0.73      0.70       133
         gac       0.84      0.85      0.85       186
         gel       0.78      0.81      0.79       232
         org       0.86      0.88      0.87       195
         pia       0.87      0.89      0.88       214
         sax       0.67      0.62      0.65       168
         tru       0.82      0.74      0.78       194
         vio       0.66      0.68      0.67       172
         voi       0.93      0.93      0.93       233

    accuracy                           0.79      2012
   macro avg       0.77      0.77      0.77      2012
weighted avg       0.79      0.79      0.79      2012



In [21]:
print(confusion_matrix(y_test, y_pre_lg))

[[ 90   2   4   0   5   1   2   5   0  17   1]
 [  7 104  10   1   4   0   2  19   5   4   2]
 [  2   5  97   6   0   6   4   7   1   3   2]
 [  3   1   2 159  11   1   6   0   1   1   1]
 [  3   3   3  11 188   6   4   1   5   5   3]
 [  0   1   7   0   9 172   3   0   2   0   1]
 [  1   1   2   7   4   5 191   0   1   2   0]
 [  6  11   5   1   8   2   4 105  11  13   2]
 [  2  12   6   1   2   2   1  11 143  12   2]
 [ 14   8   3   1   8   3   1   8   6 117   3]
 [  0   1   4   3   3   1   1   1   0   3 216]]
